//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkemy_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public short ID { get; set; }
        public short ID_Course { get; set; }
        public string Day { get; set; }
        public System.TimeSpan Start_Hour { get; set; }
        public System.TimeSpan End_Hour { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
