//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkemy_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_Course
    {
        public short ID_Course { get; set; }
        public short ID_Timetable { get; set; }
        public string Nombre { get; set; }
        public byte Capacidad { get; set; }
        public Nullable<int> Vacantes { get; set; }
        public string Dia { get; set; }
        public System.TimeSpan Hora_Incial { get; set; }
        public System.TimeSpan Hora_Final { get; set; }
    }
}
